// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AdoTemplateGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Data;
    using System.Configuration;
    using AdoTemplateGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ReaderVBADOTemplate : ReaderVBADOTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n\t\'\'Public Function cn");
            
            #line 18 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 18 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", dictionaryParameters.Select(kvp => $"{kvp.Key.Substring(4)} As {kvp.Value.Item3}").ToList())));
            
            #line default
            #line hidden
            this.Write(") As Tuple(Of List(Of ResultSetModel), Integer)\r\n\tPublic Function cn");
            
            #line 19 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("(ByVal entity As Model) As Tuple(Of List(Of ResultSetModel), Integer)\r\n\t\t\'\'Dim dt" +
                    "DataProcedure = _objDatos.cd");
            
            #line 20 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 20 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", dictionaryParameters.Select(kvp => kvp.Key.Substring(4)).ToList())));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\tDim dtDataProcedure = _objDatos.cd");
            
            #line 21 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write(@"(entity)
		Dim listData = New List(Of ResultSetModel)

		For Each iRow As DataRow In dtDataProcedure.Rows
            Dim myObj = Activator.CreateInstance(GetType(ResultSetModel))
            For Each iPropertyInfo In myObj.GetType().GetProperties()
                If Not iRow(iPropertyInfo.Name) Is DBNull.Value AndAlso Not Object.Equals(iRow(iPropertyInfo.Name), Nothing) Then
                    iPropertyInfo.SetValue(myObj, iRow(iPropertyInfo.Name), Nothing)
                End If
            Next
            Dim objectRecord = CType(myObj, ResultSetModel)
            listData.Add(objectRecord)
        Next

		Dim totalRows = If(listData.FirstOrDefault() Is Nothing, 0, listData.FirstOrDefault().TotRows)

		Return New Tuple(Of List(Of ResultSetModel), Integer)(listData, totalRows)
	End Function

	''Public Function cd");
            
            #line 40 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 40 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", dictionaryParameters.Select(kvp => $"{kvp.Key.Substring(4)} As {kvp.Value.Item3}").ToList())));
            
            #line default
            #line hidden
            this.Write(") As DataTable\r\n\tPublic Function cd");
            
            #line 41 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("(ByVal entity As Model) As DataTable\r\n\t\tReDim campoParam(");
            
            #line 42 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryParameters.Count() - 1));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\tlistParam.Clear()\r\n\t\t\r\n");
            
            #line 45 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

int iIndex = 0;
foreach(var item in dictionaryParameters)
{
	if(item.Value.Item2)
	{
		

            
            #line default
            #line hidden
            this.Write("\t\t\'Does not exists output parameters\r\n");
            
            #line 54 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\tcampoParam(");
            
            #line 59 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iIndex++));
            
            #line default
            #line hidden
            this.Write(") = New SqlParameter(\"");
            
            #line 59 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\", If(Not CType(entity.");
            
            #line 59 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key.Substring(4)));
            
            #line default
            #line hidden
            this.Write(", Object) Is Nothing, CType(entity.");
            
            #line 59 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key.Substring(4)));
            
            #line default
            #line hidden
            this.Write(", Object), DBNull.Value))\r\n");
            
            #line 60 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

	}
}

            
            #line default
            #line hidden
            this.Write("\t\tFor Each iParam In campoParam\r\n            listParam.Add(iParam)\r\n        Next\r" +
                    "\n\r\n        Return _objConexion.fdtEjecutarConsultaSP_ConParametros(\"");
            
            #line 68 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("\", listParam)\r\n\tEnd Function\r\n\r\n\r\n\tPublic Class Model\r\n");
            
            #line 73 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

foreach(var item in dictionaryParameters)
{

            
            #line default
            #line hidden
            this.Write("\t\tProperty ");
            
            #line 77 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key.Substring(4)));
            
            #line default
            #line hidden
            this.Write(" As ");
            
            #line 77 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Item3));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 78 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\tEnd Class\r\n\r\n\tPublic Class ResultSetModel\r\n");
            
            #line 84 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

foreach(var iColumn in dictionaryColumns)
{

            
            #line default
            #line hidden
            this.Write("\t\tProperty ");
            
            #line 88 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iColumn.Key));
            
            #line default
            #line hidden
            this.Write(" As ");
            
            #line 88 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iColumn.Value.DataTypeFullName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 89 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

}

            
            #line default
            #line hidden
            this.Write("\tEnd Class\r\n\r\n\r\n");
            
            #line 95 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
 foreach(var item in dictionaryParameters) { 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 95 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key.Substring(4)));
            
            #line default
            #line hidden
            this.Write(" As ");
            
            #line 95 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value.Item3));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 95 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 97 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
 foreach(var item in dictionaryParameters) { 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 97 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key.Substring(4)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 97 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n<form>\r\n\r\n");
            
            #line 101 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
foreach(var item in dictionaryColumns)
  {
            
            #line default
            #line hidden
            this.Write("  <input type=\"text\" name=\"");
            
            #line 103 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Key));
            
            #line default
            #line hidden
            this.Write("\" />\r\n\r\n");
            
            #line 105 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

  }

            
            #line default
            #line hidden
            this.Write("</form>\r\n\r\n\t$(\"#\").jtable({\r\n\t\ttitle: \'");
            
            #line 111 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(procedureName));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\tpaging: true,\r\n        pageSize: 10,\r\n        sorting: true,\r\n        defau" +
                    "ltSorting: \'");
            
            #line 115 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryColumns.Select(kvp => kvp.Key).FirstOrDefault()));
            
            #line default
            #line hidden
            this.Write(" ASC\',\r\n\t\tactions: {\r\n\t\t\tlistAction: \'\',\r\n\t\t\tcreateAction: \'\',\r\n\t\t\teditAction: \'\'" +
                    ",\r\n\t\t\tdeleteAction: \'\'\r\n\t\t},\r\n\t\tfields: {\r\n");
            
            #line 123 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

for (int i = 0; i < dictionaryColumns.Count; i++)
{
	var kvp = dictionaryColumns.ElementAt(i);
	if(i == 0)
    {

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 130 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(": {\r\n\t\t\t\tkey: true,\r\n\t\t\t\tlist: false,\r\n\t\t\t\tedit: false,\r\n\t\t\t\tcreate: false\r\n\t\t\t}," +
                    "\r\n");
            
            #line 136 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

	}
	else if(i < dictionaryColumns.Count - 1)
	{

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 141 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(": {\r\n\t\t\t\ttitle: \'");
            
            #line 142 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t\tlist: false,\r\n\t\t\t\tedit: false,\r\n\t\t\t\tcreate: false\r\n\t\t\t},\r\n");
            
            #line 147 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

    }
	else
    {

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 152 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(": {\r\n\t\t\t\ttitle: \'");
            
            #line 153 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("\',\r\n\t\t\t\tlist: false,\r\n\t\t\t\tedit: false,\r\n\t\t\t\tcreate: false\r\n\t\t\t}\r\n");
            
            #line 158 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t});\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Erick\Documents\Neo\Tools\AdoTemplateGenerator\AdoTemplateGenerator\AdoTemplateGenerator\Templates\ReaderVBADOTemplate.tt"

private string _procedureNameField;

/// <summary>
/// Access the procedureName parameter of the template.
/// </summary>
private string procedureName
{
    get
    {
        return this._procedureNameField;
    }
}

private string _connectionStringNameField;

/// <summary>
/// Access the connectionStringName parameter of the template.
/// </summary>
private string connectionStringName
{
    get
    {
        return this._connectionStringNameField;
    }
}

private global::System.Collections.Generic.Dictionary<string, System.Tuple<string, bool, string>> _dictionaryParametersField;

/// <summary>
/// Access the dictionaryParameters parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<string, System.Tuple<string, bool, string>> dictionaryParameters
{
    get
    {
        return this._dictionaryParametersField;
    }
}

private global::System.Collections.Generic.Dictionary<string, AdoTemplateGenerator.Models.ReaderColumnModel> _dictionaryColumnsField;

/// <summary>
/// Access the dictionaryColumns parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<string, AdoTemplateGenerator.Models.ReaderColumnModel> dictionaryColumns
{
    get
    {
        return this._dictionaryColumnsField;
    }
}

private string _parametersJoinedField;

/// <summary>
/// Access the parametersJoined parameter of the template.
/// </summary>
private string parametersJoined
{
    get
    {
        return this._parametersJoinedField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool procedureNameValueAcquired = false;
if (this.Session.ContainsKey("procedureName"))
{
    this._procedureNameField = ((string)(this.Session["procedureName"]));
    procedureNameValueAcquired = true;
}
if ((procedureNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("procedureName");
    if ((data != null))
    {
        this._procedureNameField = ((string)(data));
    }
}
bool connectionStringNameValueAcquired = false;
if (this.Session.ContainsKey("connectionStringName"))
{
    this._connectionStringNameField = ((string)(this.Session["connectionStringName"]));
    connectionStringNameValueAcquired = true;
}
if ((connectionStringNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("connectionStringName");
    if ((data != null))
    {
        this._connectionStringNameField = ((string)(data));
    }
}
bool dictionaryParametersValueAcquired = false;
if (this.Session.ContainsKey("dictionaryParameters"))
{
    this._dictionaryParametersField = ((global::System.Collections.Generic.Dictionary<string, System.Tuple<string, bool, string>>)(this.Session["dictionaryParameters"]));
    dictionaryParametersValueAcquired = true;
}
if ((dictionaryParametersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("dictionaryParameters");
    if ((data != null))
    {
        this._dictionaryParametersField = ((global::System.Collections.Generic.Dictionary<string, System.Tuple<string, bool, string>>)(data));
    }
}
bool dictionaryColumnsValueAcquired = false;
if (this.Session.ContainsKey("dictionaryColumns"))
{
    this._dictionaryColumnsField = ((global::System.Collections.Generic.Dictionary<string, AdoTemplateGenerator.Models.ReaderColumnModel>)(this.Session["dictionaryColumns"]));
    dictionaryColumnsValueAcquired = true;
}
if ((dictionaryColumnsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("dictionaryColumns");
    if ((data != null))
    {
        this._dictionaryColumnsField = ((global::System.Collections.Generic.Dictionary<string, AdoTemplateGenerator.Models.ReaderColumnModel>)(data));
    }
}
bool parametersJoinedValueAcquired = false;
if (this.Session.ContainsKey("parametersJoined"))
{
    this._parametersJoinedField = ((string)(this.Session["parametersJoined"]));
    parametersJoinedValueAcquired = true;
}
if ((parametersJoinedValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("parametersJoined");
    if ((data != null))
    {
        this._parametersJoinedField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ReaderVBADOTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
